# Generated by Django 3.2.5 on 2021-07-16 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nirbha_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviceconfig',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='deviceversion',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclactivitylog',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclalertdetails',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclalertmonitor',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclalertmonitorold',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclalertmonitorold2',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclalertsendreport',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclalertsettings',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclapproved',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclapprovemaster',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclcheckdata',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclcity',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclcompany',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclconstants',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='iocldealermaster',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='iocldevice',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='iocldeviceaudiolog',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='iocldevicechangelogs',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='iocldevicesetzone',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='iocldistancemovementreport',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='iocldriver',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclgeofencingzone',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclgroup',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='iocllasttrackinglog',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='iocllasttrip',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='iocllocation',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='iocllocationunknown',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclmaillog',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclmailsend',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclplantzone',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclreporttable',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclrole',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclrolemapping',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclroute',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclroutewaypoint',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclrtd',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclrtdconnect',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclrtddoc',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclrtdprocess',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclrtdrequest',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclrtdtime',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclrtdtollplaza',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclsimcardprovider',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclspeedmonitorreport',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclstate',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclstoppagereport',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='iocltollplaza',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='iocltollplaza2',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='iocltrackinglog',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='iocltrackinglogduplicate',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='iocltransportermapping',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='iocltransportervehiclemapping',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='iocltravelhistoryreport',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='iocltrip',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='iocltripinfo',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='iocltriplog',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='iocltripold',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclunregisterdata',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='iocluserloginlog',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclusers',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclvehicle',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclvehicle012021',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclvehicle022021',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclvehicle032021',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclvehicle042020',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclvehicle042021',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclvehiclecategorymaster',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclvehicleinsurance',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclvehicleold',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclvehiclepuc',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclvehiclequeue',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclvehicletmp',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclvehicletypemaster',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclvltmanufacturermaster',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclvltmodelmaster',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclwaypoint',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclzonemaster',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ioclzonetype',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='loginmst',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='rawdata2',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='rawdata22',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='rawdatab',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='rawdatab2',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='rawdatafuturedate',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='rawdatainvalid',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='rawdataitraold',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='reportmst',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='testlocation',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='trackreport',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='uptime2',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='uptime2april',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='uptime2dup',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='uptimenew3',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='waypoint',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='waypointlatlong',
            options={'managed': True},
        ),
    ]
