# Generated by Django 3.2.5 on 2021-07-16 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nirbha_api', '0002_auto_20210716_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='ioclvehiclequeue',
            name='tripid',
            field=models.ForeignKey(blank=True, db_column='tripid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nirbha_api.iocltrip'),
        ),
        migrations.AddField(
            model_name='ioclvehiclequeue',
            name='vehicleid',
            field=models.ForeignKey(blank=True, db_column='vehicleid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='nirbha_api.ioclvehicle'),
        ),
    ]
