# Generated by Django 3.2.5 on 2021-07-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keybase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='passby',
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
