# Generated by Django 3.2.12 on 2022-03-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='leave_name',
            field=models.CharField(blank=True, choices=[('ANNUAL_LEAVE', 'ANNUAL_LEAVE'), ('CASUAL_LEAVE', 'CASUAL_LEAVE'), ('SICK_LEAVE', 'SICK_LEAVE')], default='CASUAL_LEAVE', max_length=100, null=True),
        ),
    ]
